# Preface {.unnumbered}


The increasingly widespread deployment of malicious bot accounts on Twitter has been steadily developing into a major concern. It is imperative to develop a reliable method to identify and classify these bot accounts to maintain the integrity of the platform and halt the spread of misinformation, spam and harassment This report aims to address this problem by using machine learning algorithms to classify Twitter accounts as bots or humans. The report will examine the tweets and user data provided by the Twitter developer API and a research article to train the model. The model will be evaluated based on various metrics such as accuracy, precision, recall, and F1 score, and hyperparameter tuning will be performed to select the best parameters to classify bot accounts efficiently. Moreover, the report will also analyze the content of tweets to identify patterns in language and user features. To accomplish the goal of creating an effective yet reliable bot identification machine learning model, we will follow a strict structure of developing a machine learning model by undergoing data exploration, data preprocessing, model selection, and performance evaluation. Furthermore, the project includes detailed visualizations and explanations of the results, allowing the model performance to be better understand such that readers can make informed decisions about their implementations.

